version: 2.1

docker:
  - image: circleci/openjdk:14-jdk-stretch

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
